/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.mycompany.restaurant.client.presentation;

import static co.mycompany.restaurant.client.infra.Messages.successMessage;
import co.mycompany.restaurant.commons.domain.Componente;
import co.mycompany.restaurant.commons.domain.TipoComponente;


/**
 *
 * @author kevith felipe bastidas
 */
public class GUIPagAgregarComponente extends javax.swing.JFrame {
    /**
     * instancia del controlador
     */
    private static final RestaurantFacade facade = RestaurantFacade.getInstance();
    /**
     * Limpia la caja de texto
     */
    private void clean() {
        txtId.setText("");
        txtNombre.setText("");
        cbxTipoComponente.setSelectedIndex(0);

        txtNombre.setEnabled(false);
        cbxTipoComponente.setEnabled(false);
        btnAgregar.setEnabled(false);
    }
    /**
     * Constructor privado: Creates new form GUIAgregarComponente
     */
    public GUIPagAgregarComponente() {
        initComponents();
        setSize(614, 388);
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlDatosDelComponente = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblTipoComponente = new javax.swing.JLabel();
        cbxTipoComponente = new javax.swing.JComboBox<>();
        pnlTitiulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new java.awt.BorderLayout());

        pnlDatosDelComponente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlDatosDelComponente.setLayout(new java.awt.GridLayout(3, 0));

        lblId.setText("Id");
        pnlDatosDelComponente.add(lblId);

        txtId.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtIdCaretUpdate(evt);
            }
        });
        pnlDatosDelComponente.add(txtId);

        lblNombre.setText("Nombre");
        pnlDatosDelComponente.add(lblNombre);

        txtNombre.setEnabled(false);
        txtNombre.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNombreCaretUpdate(evt);
            }
        });
        pnlDatosDelComponente.add(txtNombre);

        lblTipoComponente.setText("Tipo Componente");
        pnlDatosDelComponente.add(lblTipoComponente);

        cbxTipoComponente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo", "ENTRADA", "PRINCIPIO", "PROTEINA", "BEBIDA" }));
        cbxTipoComponente.setEnabled(false);
        cbxTipoComponente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbxTipoComponenteMousePressed(evt);
            }
        });
        pnlDatosDelComponente.add(cbxTipoComponente);

        jPanel1.add(pnlDatosDelComponente, java.awt.BorderLayout.CENTER);

        pnlTitiulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlTitiulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblTitulo.setText("INGRESAR LOS DATOS DEL COMPONENTE");
        pnlTitiulo.add(lblTitulo);

        jPanel1.add(pnlTitiulo, java.awt.BorderLayout.NORTH);

        pnlButtons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlButtons.setLayout(new java.awt.GridLayout(1, 0));

        btnAgregar.setText("Agregar");
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        pnlButtons.add(btnAgregar);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        pnlButtons.add(btnVolver);

        jPanel1.add(pnlButtons, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Activa las caja de texto nombre
     * @param evt 
     */
    private void txtIdCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtIdCaretUpdate
        // TODO add your handling code here:
        txtNombre.setEnabled(true);
        txtNombre.setEditable(true);
    }//GEN-LAST:event_txtIdCaretUpdate
    /**
     * Activa el comboBox Componente si la caja de texto nombre esta activado
     * @param evt 
     */
    private void txtNombreCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNombreCaretUpdate
        // TODO add your handling code here:
        if(txtNombre.isEnabled() == true){
            cbxTipoComponente.setEnabled(true);
        }
    }//GEN-LAST:event_txtNombreCaretUpdate
    /**
     * Agrega un componente a la base de datos
     * @param evt 
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        Componente componente = new Componente();
        
        if ("".equals(txtId.getText())) {
            successMessage("Campo id vacío.", "Atención");
        }else if("".equals(txtNombre.getText())){
            successMessage("Campo Nombre vacío.", "Atención");
        }else if(cbxTipoComponente.getItemAt(cbxTipoComponente.getSelectedIndex()).equals("Seleccione un tipo")){
            successMessage("Seleccione un tipo de componente.", "Atención");
        }else{
            try {
                componente.setId(Integer.parseInt(txtId.getText()));
                componente.setNombre(txtNombre.getText());

                componente.setTipo(TipoComponente.valueOf(cbxTipoComponente.getItemAt(cbxTipoComponente.getSelectedIndex())));
                String respuesta = facade.addComponente(componente);
                boolean ban = false;
                if (respuesta.equals("Error, el componente con ese id y nombre ya existe")) {
                    ban = true;
                }else if(respuesta.equals("Error el componente con ese id y tipo de componente ya existe")) {
                    ban = true;
                }
                if(!ban){
                    clean();
                }
                successMessage(respuesta, "Atención");         
            } catch (NumberFormatException ex) {
                successMessage("Id incorrecto", "Atención");
            }            
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cbxTipoComponenteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxTipoComponenteMousePressed
        // TODO add your handling code here:
        if (cbxTipoComponente.isEnabled() == true) {
            btnAgregar.setEnabled(true);
            btnAgregar.setEnabled(true);
        }
        
    }//GEN-LAST:event_cbxTipoComponenteMousePressed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnVolverActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxTipoComponente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTipoComponente;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlDatosDelComponente;
    private javax.swing.JPanel pnlTitiulo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
